### ISSUE TITLE
snake case

### ISSUE THREAD

**Issue by comsompom** [Svajunas900/Leetcode_Problems#4]
https://github.com/Svajunas900/Leetcode_Problems/blob/92018dc18ce934b9df8527160eec7204e1ddf6b8/problem_2109.py#L5C13-L5C25

in the clean code it is like the defacto standard for some organisation to use the snake case in the python scripting.

Lets make for the future scripts this - like internal standard - just snake case

**Comment by Svajunas900** [comment]
Okay
